<%--
  Created by IntelliJ IDEA.
  User: zhaomeng
  Date: 12-8-26
  Time: 下午12:10
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
       <html>
       <head>
           <%@include file="../snippet/meta.jsp"%>
       </head>
       <body>
       <div id="wrapper">
           <%@include file="../snippet/header.jsp"%>
           <div id="content">
               <div id="aside">

               </div>

               <div id="article">

               </div>
           </div>
           <div class="clr"></div>
           <%@include file="../snippet/footer.jsp"%>
       </div>
       </body>
       </html>